-- Meeting stone -> the DUNGEON it summons to, for pfQuest Reforged.
-- GENERATED by tools/gen_meetingstone335.py, do not hand-edit.
--
-- Source: AzerothCore world database, gameobject_template, type 23
-- (GAMEOBJECT_TYPE_MEETINGSTONE) Data2 = the dungeon's areaID, from
-- github.com/azerothcore/azerothcore-wotlk, data/sql/base/db_world,
-- commit 1883e5c5e07504212ca36d307e51075528db9633.
--
-- Every meeting stone in the game is named "Meeting Stone", so a marker
-- could only ever say that. The areaID here IS pfQuest's zone id space, so
-- consumers resolve the name through pfDB["zones"]["loc"] and nothing
-- extra ships or needs translating.
--
-- Shape: pfDB["meetingstone335"][objectId] = zoneId. Only stones pfQuest
-- tracks in meta["meetingstone"] are emitted (31 skipped as untracked),
-- and only where the areaID resolves to a name (1 skipped as unnamed);
-- a stone we cannot name keeps the plain "Meeting Stone" label.
pfDB["meetingstone335"] = {
  [178824] = 722, -- Razorfen Downs
  [178825] = 491, -- Razorfen Kraul
  [178826] = 2557, -- Dire Maul
  [178827] = 2100, -- Maraudon
  [178828] = 719, -- Blackfathom Deeps
  [178829] = 978, -- Zul\'Farrak
  [178831] = 2017, -- Stratholme
  [178832] = 2057, -- Scholomance
  [178833] = 1517, -- Uldaman
  [178834] = 1581, -- The Deadmines
  [178844] = 796, -- Scarlet Monastery
  [178845] = 209, -- Shadowfang Keep
  [178884] = 718, -- Wailing Caverns
  [179554] = 1477, -- The Temple of Atal\'Hakkar
  [179555] = 133, -- Gnomeregan
  [179584] = 1584, -- Blackrock Depths
  [179585] = 1583, -- Blackrock Spire
  [179586] = 1584, -- Blackrock Depths
  [179587] = 1583, -- Blackrock Spire
  [179595] = 717, -- The Stockade
  [179596] = 2437, -- Ragefire Chasm
}
