#!/usr/bin/env python3
"""Generate db/quests-skillrank335.lua -- the profession SKILL RANK a quest
requires, from an AzerothCore world DB.

Why this exists
---------------
pfQuest models a profession requirement as "do you have this skill at all"
(quests[id]["skill"] is a SkillLine id, and QuestFilter checks presence only).
The rank is nowhere in the data, so a level-35 player with First Aid 150 was
shown "Horde Trauma", which needs First Aid 225 -- reported from in-game QA,
along with the cooking and fishing quests of the same shape.

AzerothCore carries both halves in quest_template_addon: RequiredSkillID and
RequiredSkillPoints. This tool emits the points, plus the skill id for the
quests where pfQuest carries no ["skill"] field at all (59 of them -- those
were not merely mis-ranked, they were completely ungated).

Source data
-----------
    SHA=$(git ls-remote https://github.com/azerothcore/azerothcore-wotlk.git refs/heads/master | cut -f1)
    mkdir -p ~/refs/ac-world && cd ~/refs/ac-world && echo "$SHA" > sha.txt
    curl -sSL -O "https://raw.githubusercontent.com/azerothcore/azerothcore-wotlk/$SHA/data/sql/base/db_world/quest_template_addon.sql"

Then run from the addon root:

    python3 tools/gen_questskill335.py --ac-dir ~/refs/ac-world

Trust model
-----------
Emitted only for quests pfQuest actually knows. Where BOTH sources name a
skill they are required to AGREE: a disagreement is a data conflict this tool
refuses to paper over, so it fails loudly rather than emitting a guess.
"""

import argparse
import os
import re
import sys

# quest_template_addon column order (0-based), from the AC schema
COL_ID = 0
COL_SKILL_ID = 10
COL_SKILL_POINTS = 11


def read_rows(path):
    """Every VALUES tuple of the dump. The INSERT spans many lines, so the
    statement cannot be parsed line-by-line."""
    with open(path, encoding="utf8", errors="replace") as fh:
        text = fh.read()
    marker = "INSERT INTO `quest_template_addon` VALUES"
    if marker not in text:
        sys.exit("no quest_template_addon INSERT in %s" % path)
    body = text[text.index(marker):]
    return [m.group(1).split(",") for m in re.finditer(r"\(([^()]*)\)", body)]


def read_pfquest_skills(root):
    """quest id -> SkillLine id (or None) as pfQuest's own data has it. Later
    files win, mirroring the overlay order the addon merges in."""
    skills = {}
    for name in ("db/quests.lua", "db/quests-tbc.lua", "db/quests-wotlk.lua"):
        path = os.path.join(root, name)
        if not os.path.exists(path):
            continue
        with open(path, encoding="utf8", errors="replace") as fh:
            text = fh.read()
        for m in re.finditer(r"\n  \[(\d+)\] = \{(.*?)\n  \},", text, re.S):
            found = re.search(r'\["skill"\] = (\d+)', m.group(2))
            skills[int(m.group(1))] = int(found.group(1)) if found else None
    return skills


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ac-dir", default=os.path.expanduser("~/refs/ac-world"))
    ap.add_argument("--out", default="db/quests-skillrank335.lua")
    args = ap.parse_args()

    root = os.getcwd()
    known = read_pfquest_skills(root)
    if not known:
        sys.exit("no pfQuest quest data found -- run from the addon root")

    rows = read_rows(os.path.join(args.ac_dir, "quest_template_addon.sql"))
    sha = ""
    shafile = os.path.join(args.ac_dir, "sha.txt")
    if os.path.exists(shafile):
        sha = open(shafile).read().strip()

    emitted, skipped_unknown, added_skill, conflicts = {}, 0, 0, []
    for row in rows:
        try:
            qid = int(row[COL_ID])
            skill_id = int(row[COL_SKILL_ID])
            points = int(row[COL_SKILL_POINTS])
        except (ValueError, IndexError):
            continue
        if points <= 0:
            continue
        if qid not in known:
            skipped_unknown += 1
            continue
        theirs = known[qid]
        if theirs is not None and skill_id and theirs != skill_id:
            conflicts.append((qid, theirs, skill_id))
            continue
        entry = {"rank": points}
        if theirs is None and skill_id:
            entry["skill"] = skill_id
            added_skill += 1
        emitted[qid] = entry

    if conflicts:
        for qid, theirs, ours in conflicts[:20]:
            print("CONFLICT quest %d: pfQuest skill %s, AC skill %s"
                  % (qid, theirs, ours), file=sys.stderr)
        sys.exit("%d skill-id conflicts -- refusing to emit a guess" % len(conflicts))

    lines = [
        "-- Profession SKILL RANK requirements for pfQuest Reforged.",
        "-- GENERATED by tools/gen_questskill335.py, do not hand-edit.",
        "--",
        "-- Source: AzerothCore world database, quest_template_addon",
        "-- (RequiredSkillID, RequiredSkillPoints), from",
        "-- github.com/azerothcore/azerothcore-wotlk, data/sql/base/db_world,",
        "-- commit %s." % (sha or "(unpinned)"),
        "--",
        "-- pfQuest models a profession requirement as presence only -- quests[id]",
        "-- [\"skill\"] is a SkillLine id and QuestFilter asks whether the player has",
        "-- that skill, never at what rank. So a level-35 player with First Aid 150",
        "-- was offered \"Horde Trauma\", which needs 225 (in-game QA report), and the",
        "-- same for the cooking and fishing chains.",
        "--",
        "-- Shape: pfDB[\"quests\"][\"skillrank\"][questid] = { rank = points",
        "-- [, skill = skillLineId] }. Applied FIELD-WISE in database.lua (never",
        "-- through patchtable, which would replace the whole quest entry), after",
        "-- the tbc/wotlk overlays have merged. The optional skill slot is emitted",
        "-- only where pfQuest carries no skill id of its own: %d quests that were" % added_skill,
        "-- not merely mis-ranked but entirely ungated.",
        "--",
        "-- Where both sources name a skill they agree on every one of the %d"
        % (len(emitted) - added_skill),
        "-- entries; the generator fails rather than emit a guess if they ever do not.",
        "-- %d rank-gated quests in the server DB are unknown to pfQuest and dropped."
        % skipped_unknown,
        'pfDB["quests"]["skillrank"] = {',
    ]
    for qid in sorted(emitted):
        entry = emitted[qid]
        if "skill" in entry:
            lines.append("  [%d] = { [\"rank\"] = %d, [\"skill\"] = %d },"
                         % (qid, entry["rank"], entry["skill"]))
        else:
            lines.append("  [%d] = { [\"rank\"] = %d }," % (qid, entry["rank"]))
    lines.append("}")
    lines.append("")

    with open(os.path.join(root, args.out), "w", encoding="utf8") as fh:
        fh.write("\n".join(lines))
    print("%s: %d quests (%d also gained a skill id), %d unknown to pfQuest dropped"
          % (args.out, len(emitted), added_skill, skipped_unknown))


if __name__ == "__main__":
    main()
